/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pecl3;

import java.sql.*;
/**
 *
 * @author enrique
 */
public class PECL3 extends javax.swing.JFrame {

    Connection c;
    
    public PECL3() {
        initComponents();
        PanelEnunciado.setEditable(false);
        TextPanel.setEditable(false);
    }
    
    public Connection conectar() {
        TextPanel.setText("Probando el driver");
        
        //Nos registramos en el registro
        try {
           Class.forName("org.postgresql.Driver");
        } catch (ClassNotFoundException cnfe) {
            TextPanel.setText("Driver no disponible");
            TextPanel.setText("ERROR");
            System.out.println(cnfe.getMessage());
            System.exit(1);
        }
        TextPanel.setText("Driver Cargando. Conectando...");
        //Tomamos los datos de los usuarios
        Connection conec = null;

        String selecNombre, selecContrasena;
        selecNombre = jComboBox1.getSelectedItem().toString();
        selecContrasena = TextContrasena.getText().toString();
        String nombre = selecNombre;
        String contrasena = selecContrasena;
        try {
            conec = DriverManager.getConnection("jdbc:postgresql://localhost:5433/PecL3",
                    nombre, contrasena);
        } catch (SQLException se) {
            TextPanel.setText("Conexion no establecida.");
            System.out.println(se.getMessage());
            System.exit(1);
        }

        if (conec != null) {
            TextPanel.setText("Conectado como " + nombre);
        } else {
            TextPanel.setText("PROBLEMA NO ESPECIFICADO");
        }
        return conec;
    }
    
    public void finalizarConexion(Connection c) {
        try {
            c.close();
            TextPanel.setText("Conexión cerrada en la BD");
        } catch (SQLException e) {
            TextPanel.setText("Error al cerrar la conexión");
        }
    }
    
     public void consulta(Connection c, String consulta, int columnas) throws SQLException {

        String res = "";
        Statement s = c.createStatement();
        ResultSet rs = s.executeQuery(consulta);
        while (rs.next()) {
            res = res + "\n";
            for (int i = 1; i <= columnas; i++) {
                res = res + rs.getString(i);
                res = res + " | ";
            }
            Panel.setText(res);
        }

    }
    
    /**
     * Creates new form PECL3
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextPanel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        LoginLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextContrasena = new javax.swing.JTextField();
        consulta1 = new javax.swing.JButton();
        consulta2 = new javax.swing.JButton();
        consulta3 = new javax.swing.JButton();
        consulta12 = new javax.swing.JButton();
        consulta4 = new javax.swing.JButton();
        consulta5 = new javax.swing.JButton();
        consulta6 = new javax.swing.JButton();
        consulta11 = new javax.swing.JButton();
        consulta7 = new javax.swing.JButton();
        consulta8 = new javax.swing.JButton();
        consulta9 = new javax.swing.JButton();
        consulta10 = new javax.swing.JButton();
        consulta13 = new javax.swing.JButton();
        consulta14 = new javax.swing.JButton();
        consulta15 = new javax.swing.JButton();
        consulta16 = new javax.swing.JButton();
        consulta17 = new javax.swing.JButton();
        consulta18 = new javax.swing.JButton();
        consulta19 = new javax.swing.JButton();
        consulta20 = new javax.swing.JButton();
        consulta21 = new javax.swing.JButton();
        consulta22 = new javax.swing.JButton();
        consulta23 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelEnunciado = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Conectar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Desconectar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "postgres", "Administrador", "Gestor", "Cajero" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        LoginLabel.setText("Login:");

        jLabel1.setText("Contrasena:");

        consulta1.setText("Consulta 1");
        consulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta1ActionPerformed(evt);
            }
        });

        consulta2.setText("Consulta 2");
        consulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta2ActionPerformed(evt);
            }
        });

        consulta3.setText("Consulta 3");
        consulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta3ActionPerformed(evt);
            }
        });

        consulta12.setText("Consulta 12");
        consulta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta12ActionPerformed(evt);
            }
        });

        consulta4.setText("Consulta 4");
        consulta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta4ActionPerformed(evt);
            }
        });

        consulta5.setText("Consulta 5");
        consulta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta5ActionPerformed(evt);
            }
        });

        consulta6.setText("Consulta 6");
        consulta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta6ActionPerformed(evt);
            }
        });

        consulta11.setText("Consulta 11");
        consulta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta11ActionPerformed(evt);
            }
        });

        consulta7.setText("Consulta 7");
        consulta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta7ActionPerformed(evt);
            }
        });

        consulta8.setText("Consulta 8");
        consulta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta8ActionPerformed(evt);
            }
        });

        consulta9.setText("Consulta 9");
        consulta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta9ActionPerformed(evt);
            }
        });

        consulta10.setText("Consulta 10");
        consulta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta10ActionPerformed(evt);
            }
        });

        consulta13.setText("Consulta 13");
        consulta13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta13ActionPerformed(evt);
            }
        });

        consulta14.setText("Consulta 14");
        consulta14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta14ActionPerformed(evt);
            }
        });

        consulta15.setText("Consulta 15");
        consulta15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta15ActionPerformed(evt);
            }
        });

        consulta16.setText("Consulta 16");
        consulta16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta16ActionPerformed(evt);
            }
        });

        consulta17.setText("Consulta 17");
        consulta17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta17ActionPerformed(evt);
            }
        });

        consulta18.setText("Consulta 18");
        consulta18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta18ActionPerformed(evt);
            }
        });

        consulta19.setText("Consulta 19");
        consulta19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta19ActionPerformed(evt);
            }
        });

        consulta20.setText("Consulta 20");
        consulta20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta20ActionPerformed(evt);
            }
        });

        consulta21.setText("Consulta 21");
        consulta21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta21ActionPerformed(evt);
            }
        });

        consulta22.setText("Consulta 22");
        consulta22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta22ActionPerformed(evt);
            }
        });

        consulta23.setText("Consulta 23");
        consulta23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta23ActionPerformed(evt);
            }
        });

        PanelEnunciado.setColumns(20);
        PanelEnunciado.setRows(5);
        jScrollPane1.setViewportView(PanelEnunciado);

        Panel.setColumns(20);
        Panel.setRows(5);
        jScrollPane2.setViewportView(Panel);

        jButton3.setText("Insertar Vacuna");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Crear Cajero");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LoginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TextContrasena)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(consulta10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(consulta7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(consulta4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(consulta1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(consulta13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(consulta16)
                                    .addComponent(consulta19))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(consulta20)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(consulta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(consulta5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(consulta8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(consulta11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(consulta14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(consulta17))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(consulta3)
                                                    .addComponent(consulta6)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(consulta21)
                                                        .addGap(0, 14, Short.MAX_VALUE))
                                                    .addComponent(consulta12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(consulta9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(consulta15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(consulta18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(85, 85, 85))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consulta22)
                                .addGap(18, 18, 18)
                                .addComponent(consulta23)
                                .addGap(133, 133, 133))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginLabel)
                    .addComponent(consulta1)
                    .addComponent(consulta2)
                    .addComponent(consulta3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consulta4)
                    .addComponent(consulta5)
                    .addComponent(consulta6))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(consulta7)
                    .addComponent(consulta8)
                    .addComponent(consulta9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consulta10)
                            .addComponent(consulta11)
                            .addComponent(consulta12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consulta13)
                            .addComponent(consulta14)
                            .addComponent(consulta15)))
                    .addComponent(TextPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consulta16)
                    .addComponent(consulta17)
                    .addComponent(consulta18)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consulta19)
                    .addComponent(consulta20)
                    .addComponent(consulta21)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consulta22)
                    .addComponent(consulta23))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(520, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            // TODO add your handling code here:
            c = conectar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        finalizarConexion(c);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void consulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta1ActionPerformed
        // TODO add your handling code here:
         try {
             PanelEnunciado.setText("Obtener el total de dinero facturado por el zoo debido a las entradas y debido\n" +
"a los tickets vendidos en los restaurantes desde la implementación de la base\n" +
"de datos.");
            consulta(c,"SELECT  SUM(totalDinero) totalDinero\n" +
"FROM ( \n" +
"	select SUM(\"Precio con IVA\") totalDinero from public.\"Entradas\"\n" +
"	UNION ALL\n" +
"	select SUM(\"Precio con IVA\") totalDinero from public.\"Ticket\"\n" +
"     ) \n" +
"AS totalDinero\n" +
"        ", 1); 

        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta1ActionPerformed

    private void consulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta2ActionPerformed
        // TODO add your handling code here:
         try {
             PanelEnunciado.setText("Determinar el número total de animales que hay en el zoo y el número total\n" +
"de empleados.");
            consulta(c,"SELECT  (\n" +
"        SELECT COUNT(*)\n" +
"        FROM   public.\"Animales\"\n" +
"        ) AS Animales,\n" +
"        (\n" +
"        SELECT COUNT(*)\n" +
"        FROM   public.\"Empleados\"\n" +
"        ) AS Empleados", 2); 

        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta2ActionPerformed

    private void consulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta3ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Mostrar el nombre de los empleados que se encuentran en la categoría de\n" +
"limpieza, así como su zona asignada de limpieza.");
            consulta(c,"SELECT w1.\"DNI\", w1.\"Nombre\", w2.\"Lugar\"\n" +
"FROM public.\"Empleados\" \"w1\", public.\"Personal de Limpieza\" \"w2\"\n" +
"WHERE w1.\"DNI\" = w2.\"DNI\";", 3); 

        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta3ActionPerformed

    private void consulta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta4ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Mostrar el número de entradas vendidas que no son de tipo “especial” y su\n" +
"importe recaudado");
            consulta(c,"SELECT COUNT(\"Codigo_Entrada\") AS Numero, SUM(\"Precio con IVA\") AS ImporteTotal\n" +
"FROM public.\"Entradas\"\n" +
"WHERE \"Tipo\" != 'Especial';", 2); 

        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta4ActionPerformed

    private void consulta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta5ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Mostrar el importe medio gastado por los clientes online que están\n" +
"registrados en la base de datos.");
            consulta(c,"SELECT AVG(\"Precio con IVA\"::numeric), w1.\"Nombre de Usuario\"\n" +
"FROM public.\"Entradas\" \"w1\", public.\"Cliente Online\" \"w2\"\n" +
"WHERE w1.\"Nombre de Usuario\" = w2.\"Nombre de Usuario\"\n" +
"GROUP BY w1.\"Nombre de Usuario\";", 2); 

        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta5ActionPerformed

    private void consulta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta6ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Mostrar el porcentaje de entradas vendidas de forma online");
            consulta(c,"SELECT count(w1.\"Nombre de Usuario\")*100/count(w1.\"Codigo_Entrada\")\n" +
"  FROM public.\"Entradas\" \"w1\";", 1); 

        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta6ActionPerformed

    private void consulta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta7ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText(". Mostrar el importe total devuelto a los clientes (debido a entradas y tickets)\n" +
"en todos los sorteos realizados hasta la fecha.");
            consulta(c,"SELECT SUM(w1.\"Precio con IVA\") AS entradas, SUM(w2.\"Precio con IVA\") AS tickets\n" +
"FROM public.\"Entradas\" \"w1\", public.\"Sorteo\" \"w3\", public.\"Ticket\" \"w2\"\n" +
"WHERE w1.\"Codigo_Entrada\" = w3.\"Codigo_Entrada\"\n" +
"AND w2.\"Codigo_Ticket\" = w3.\"Codigo_Ticket\";", 1); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta7ActionPerformed

    private void consulta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta8ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Determinar el grado de satisfacción medio de las opiniones que los clientes\n" +
"han realizado por internet, mostrando la puntuación media");
            consulta(c,"SELECT avg(\"Puntuacion\")\n" +
"FROM public.\"Opinion\"", 1); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta8ActionPerformed

    private void consulta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta9ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Determinar el empleado que más entradas ha adquirido y el dinero que se ha\n" +
"ahorrado según el descuento aplicado.");
            consulta(c,"SELECT \"DNI\", contador, (((24.4::float8::numeric::money)*contador) - (17::float8::numeric::money)*contador)\n" +
"FROM (SELECT \"DNI\", COUNT(\"DNI\") contador\n" +
"	  FROM public.\"Entradas\"\n" +
"	  GROUP BY \"DNI\") AS T1\n" +
"WHERE contador IN (SELECT MAX(contador)\n" +
"				   FROM (SELECT \"DNI\", COUNT(\"DNI\") contador\n" +
"				         FROM public.\"Entradas\"\n" +
"				         GROUP BY \"DNI\") AS T2\n" +
"			 )", 3); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta9ActionPerformed

    private void consulta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta10ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Obtener el importe total que el zoo no ha recaudado en sus ofertas 2x1.");
            consulta(c,"SELECT SUM(\"Precio con IVA\")\n" +
"FROM public.\"Entradas\", public.\"Oferta\"\n" +
"WHERE \"Entradas\".\"Fecha_Entrada\" = \"Oferta\".\"Fecha\"", 1); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta10ActionPerformed

    private void consulta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta11ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Determinar el número de tickets que ha emitido cada restaurante, mostrando\n" +
"el número de tickets y el nombre del restaurante. Ordenar la salida de mayor\n" +
"a menor.");
            consulta(c,"SELECT COUNT(\"Nombre\") numero\n" +
"FROM public.\"Ticket\"\n" +
"GROUP BY \"Nombre\"\n" +
"ORDER BY numero DESC;", 1); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta11ActionPerformed

    private void consulta12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta12ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Determinar el importe total facturado debido a los clientes que han comprado\n" +
"físicamente las entradas y por los clientes que han realizado la compra por\n" +
"internet.");
            consulta(c,"SELECT  SUM(totalDinero) totalDinero\n" +
"FROM ( \n" +
"	SELECT SUM(\"Precio con IVA\") totalDinero FROM public.\"Entradas\"\n" +
"	WHERE \"DNI\" IS NULL\n" +
"	AND \"Nombre de Usuario\" IS NULL\n" +
"	UNION ALL\n" +
"	SELECT SUM(\"Precio con IVA\") totalDinero FROM public.\"Entradas\" \"w1\", public.\"Cliente Online\" \"w2\"\n" +
"	WHERE w1.\"Nombre de Usuario\" = w2.\"Nombre de Usuario\"\n" +
"     ) \n" +
"AS totalDinero", 1); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta12ActionPerformed

    private void consulta13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta13ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Mostrar el peso medio y el tamaño medio de los peces del zoo.");
            consulta(c,"SELECT AVG(\"Peso\"), AVG(\"Tamanio\")\n" +
"FROM public.\"Peces\";", 2); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta13ActionPerformed

    private void consulta14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta14ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Determinar el número trabajadores que tiene cada restaurante ordenando la\n" +
"salida de menor a mayor.");
            consulta(c,"SELECT COUNT(w1.\"DNI\") numero, w1.\"Nombre\"\n" +
"FROM public.\"Restauracion\" \"w1\", public.\"Restaurante\" \"w2\"\n" +
"WHERE w1.\"Nombre\" = w2.\"Nombre\"\n" +
"GROUP BY w1.\"DNI\"\n" +
"ORDER BY numero;", 2); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta14ActionPerformed

    private void consulta15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta15ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Mostrar el porcentaje de mamíferos carnívoros, herbívoros y omnívoros que\n" +
"viven en el zoo");
            consulta(c,"SELECT w1.\"Tipo de Comida\", count(w1.\"Codigo\") as tipo, \n" +
"( SELECT COUNT(w1.\"Tipo de Comida\")*100/count(mami.\"Codigo\")\n" +
"  FROM public.\"Mamiferos\" AS mami\n" +
") as porcentaje\n" +
"FROM public.\"Mamiferos\" \"w1\"\n" +
"GROUP BY w1.\"Tipo de Comida\";", 3); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta15ActionPerformed

    private void consulta16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta16ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Muestra el nombre y dni de los empleados que han consumido el máximo de\n" +
"las 10 entradas anuales con descuento");
            consulta(c,"SELECT COUNT(w2.\"DNI\"), w2.\"Nombre\"\n" +
"FROM public.\"Entradas\" \"w1\", public.\"Empleados\" \"w2\"\n" +
"WHERE w1.\"DNI\" = w2.\"DNI\"\n" +
"GROUP BY w2.\"DNI\"\n" +
"ORDER BY COUNT(w2.\"DNI\") DESC;", 2); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta16ActionPerformed

    private void consulta17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta17ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Muestra el nombre y el email de los empleados que trabajan en turno de\n" +
"tarde.");
            consulta(c,"SELECT \"Nombre\", \"Correo Electronico\"\n" +
"FROM public.\"Empleados\"\n" +
"WHERE \"Turno\" = 'Tarde';", 2); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta17ActionPerformed

    private void consulta18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta18ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Indicar el importe total facturado por el zoo en los días de oferta 2x1,\n" +
"indicando el número de entradas vendidas y el importe total facturado");
            consulta(c,"SELECT count(w2.\"Fecha_Oferta\"), SUM(w2.\"Precio con IVA\") \n" +
"FROM public.\"Oferta\" \"w1\", public.\"Entradas\" \"w2\"\n" +
"WHERE w1.\"Fecha\" = w2.\"Fecha_Oferta\";", 2); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta18ActionPerformed

    private void consulta19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta19ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Mostrar el número de animales que hay en cada una de las 4 categorías\n" +
"ordenando de mayor a menor.");
            consulta(c,"SELECT COUNT(\"Codigo\") numero\n" +
"FROM public.\"Animales\"\n" +
"GROUP BY \"Tipo\"\n" +
"ORDER BY numero DESC;", 1); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta19ActionPerformed

    private void consulta20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta20ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Mostrar las fechas en las que no se pueden visitar los reptiles.");
            consulta(c,"SELECT \"Fecha\"\n" +
"FROM public.\"Dias no visitables\"", 1); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta20ActionPerformed

    private void consulta21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta21ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Mostrar el dni y el nombre de los cuidadores que hayan cuidado a todos los\n" +
"mamíferos del recinto R1.");
            consulta(c,"SELECT w1.\"Ubicacion\", w2.\"Nombre\", w2.\"DNI\"\n" +
"FROM public.\"Animales\" \"w1\", public.\"Empleados\" \"w2\"\n" +
"WHERE w1.\"Ubicacion\" LIKE 'R1'\n" +
"AND w1.\"DNI\" = w2.\"DNI\";", 3); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta21ActionPerformed

    private void consulta22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta22ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Mostrar el número de hembras preñadas.");
            consulta(c,"SELECT \"Nombre Comun\"\n" +
"FROM public.\"Animales\" \"w1\", public.\"Mamiferos\" \"w2\"\n" +
"WHERE w1.\"Codigo\" = w2.\"Codigo\"\n" +
"AND w2.\"Preniada\" = TRUE;", 1); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta22ActionPerformed

    private void consulta23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta23ActionPerformed
        // TODO add your handling code here:
        try {
            PanelEnunciado.setText("Muestra el dni de los cuidadores que trabajan en el turno de tarde.");
            consulta(c,"SELECT \"DNI\"\n" +
"FROM public.\"Empleados\"\n" +
"WHERE \"Turno\" = 'Tarde'\n" +
"AND \"Tipo\" = 'Cuidador';", 1); 
        } catch (SQLException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_consulta23ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Insercion i = new Insercion(c);
        i.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CrearRol cr = new CrearRol(c);
        cr.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PECL3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PECL3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PECL3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PECL3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PECL3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JTextArea Panel;
    private javax.swing.JTextArea PanelEnunciado;
    private javax.swing.JTextField TextContrasena;
    private javax.swing.JTextField TextPanel;
    private javax.swing.JButton consulta1;
    private javax.swing.JButton consulta10;
    private javax.swing.JButton consulta11;
    private javax.swing.JButton consulta12;
    private javax.swing.JButton consulta13;
    private javax.swing.JButton consulta14;
    private javax.swing.JButton consulta15;
    private javax.swing.JButton consulta16;
    private javax.swing.JButton consulta17;
    private javax.swing.JButton consulta18;
    private javax.swing.JButton consulta19;
    private javax.swing.JButton consulta2;
    private javax.swing.JButton consulta20;
    private javax.swing.JButton consulta21;
    private javax.swing.JButton consulta22;
    private javax.swing.JButton consulta23;
    private javax.swing.JButton consulta3;
    private javax.swing.JButton consulta4;
    private javax.swing.JButton consulta5;
    private javax.swing.JButton consulta6;
    private javax.swing.JButton consulta7;
    private javax.swing.JButton consulta8;
    private javax.swing.JButton consulta9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
